### PR TITLE
minor readme edit

### PR DESCRIPTION
**Pull request by joshxfi**
- match the color of `MIT license` badge to others 
License

- add link for `PayMongo`

### CODE REVIEW

**Comment by princejoogie** [comment]
@joshxfi  also have some minor changes needed in the README. 

in payment method, the details are in `snake case` format, but in the actual code it's in `camel case`.

image
image

can you check if there are still remaining snake case in the source code and change them to camelCase and update the docs for them as well. thanks!

**Comment by princejoogie** [comment]
while you're at it, can you also check if we have covered all features? meaning all props needed according to [API Reference](https://developers.paymongo.com/reference/getting-started-with-your-api)

**Comment by joshxfi** [comment]
sure thing

**Comment by joshxfi** [comment]
checked all props from the api reference, seems like we got all the props needed.

**Comment by princejoogie** [comment]
can you direct this PR to `dev`?

**Pull request merged**
